version: '3'
services:
  client:
    build: ./Client
    ports:
      - "5173:5173"
    depends_on:
      - flask-server
      - db
  flask-server:
    build: ./Server
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deepface
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9906:3306"
    volumes:
      - "./DB:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./grafana/prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=${PROMETHEUS_RETENTION:-24h}
    restart: always
    networks:
      - monitor-net
  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - monitor-net


networks:
  monitor-net:
    driver: bridge