version: '3'
services:
  admin:
    build: ./Admin
    ports:
      - "2112:2112"
    depends_on:
      - flask-server
      - database
  kiosk:
    build: ./Kiosk
    ports:
      - "5173:5173"
    depends_on:
      - flask-server
      # - database
  flask-server:
    build: ./Server
    restart: always
    ports:
      - "3001:3001"
    # depends_on:
    #   - database
    environment:
      - TZ=Asia/Bangkok
    env_file:
      - ./Server/.env
  database:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deepface
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9907:3307"
    volumes:
      - "./DB:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database
