version: '3'
services:
  client:
    build: ./Client
    ports:
      - "5173:5173"
    depends_on:
      - flask-server
  flask-server:
    build: ./Server
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deepface
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9906:3306"
    volumes:
      - "./DB:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
