global:
  scrape_interval: 8s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 8s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'job-prometheus'
    scrape_interval: 9s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: "job-node-exporter"
    scrape_interval: 9s
    static_configs:
      - targets: ["node-exporter:9100"]
